title: ABIMAEL ORTIZ # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ART PORTFOLIO 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.instagram.com/abimaelortiz/">View My Instagram Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
